version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '90:80'
      - '91:81'
      - '443:443'
    volumes:
      - /opt/titan/.scripts/npm/config.json:/app/config/production.json
      - /titan/appdata/npm/data:/data
      - /titan/appdata/npm/letsencrypt:/etc/letsencrypt
  db:
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'focal'
      MYSQL_PASSWORD: '9876@@'
    volumes:
      - /titan/appdata/npm/data/mysql:/var/lib/mysql