---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Core - Services:
    - Titan Proxy:
        href: http://192.168.7.254:91
        description: ... ...
        icon: nginx-proxy-manager.png
        ping: 192.168.7.254
        container: npm-app
        widget:
          type: npm
          url: http://192.168.7.254:91
          username: seni@cityplug.co.uk
          password: Szxs234.
    - Nextcloud:
        href: http://192.168.7.254:8080
        description: ... ... ...
        icon: nextcloud.png
        ping: 192.168.7.254
        container: nextcloud
        widget:
          type: nextcloud
          url: http://192.168.7.254:8080
          username: focal
          password: Szxs234.

- Secondary - Services:
    - Pihole:
        href: http://192.168.7.254/admin
        description: ...
        icon: pi-hole.png
        ping: 192.168.7.254
        container: pihole
        widget:
          type: pihole
          url: http://192.168.7.254
          key: 28c361af2b72518bbb6c37405f604461c1a4143d4f9af9d99b16be5a25765aa3
    - Portainer:
        href: https://192.168.7.254:9443
        description: ... ... ... ...
        icon: portainer.png
        ping: 192.168.7.254
        container: portainer
        widget:
          type: portainer
          url: https://192.168.7.254:9443
          env: 2
          key: ptr_DVOfwJakP1G7UZLbQlF5uPPogyMZ1Voo15tcO4f9c5s=

- Remote - Services:
    - Unifi Portal:
        href: https://unifi.ui.com/consoles
        description: ... ...
        icon: unifi.png
        ping: https://unifi.ui.com/consoles
        widget:
          type: unifi
          url: https://unifi.host.or.ip:port
          username: username
          password: password
          site: Site Name # optional
    - Reolink:
        icon: channels.png
        href: http://192.168.7.***
        description: ... ...
        ping:
    - Alfa:
        href: http://192.168.10.254
        description: ... ...
        icon: baserow.png
        ping: 192.168.10.254
