---
title: "Titan Dashboard"
subtitle: "Home"

header: false
footer: '<p><a href="https://redi1.soccerstreams.net/"><i class="fas fa-futbol"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www3.gogoanime.cm/category/shingeki-no-kyojin-the-final-season-part-2"><i class="fas fa-dragon"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://anydesk.com/uk/downloads/thank-you?dv=win_exe"><i class="fas fa-download"></i></a></p>'
target: "_blank" # optional html a tag target attribute

stylesheet:
  - "assets/custom.css"

columns: "3" # Change this to any number: (1, 2, 3, 4, 6, 12)
colors:
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

  light:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

links:
 - name: "Google.co.uk"
   icon: "fa-brands fa-google"
   url: "https://www.google.co.uk/?gws_rd=ssl"
   target: "_blank" # optional html a tag target attribute
 - name: "CloudFlare"
   icon: "fa-brands fa-cloudflare"
   url: "https://www.youtube.com/"
   target: "_blank" # optional html a tag target attribute
 - name: "Youtube"
   icon: "fa-brands fa-youtube"
   url: "https://www.youtube.com/"
   target: "_blank" # optional html a tag target attribute
 - name: "Router"
   icon: "fa-solid fa-network-wired"
   url: "https://192.168.7.1"
   target: "_blank" # optional html a tag target attribute
 - name: "Tailscale"
   icon: "fa-solid fa-layer-group"
   url: "https://login.tailscale.com/admin/machines"
   target: "_blank" # optional html a tag target attribute 

services:
  - name: "Core - Services"
    icon: "fa-solid fa-server"
    items:
      - name: "Titan Proxy"
        logo: "assets/tools/npm.png"
        subtitle: "... ..."
        tag: "core"
        tagstyle: "is-warning"
        url: "http://192.168.7.254:91"
        target: "_blank" # optional html a tag target attribute
      - name: "ReoLink"
        logo: "assets/tools/reo.png"
        subtitle: "... ..."
        tag: "core"
        tagstyle: "is-warning"
        url: "http://192.168.7.***/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pihole"
        logo: "assets/tools/pihole.png"
        subtitle: "... ..."
        tag: "app1"
        tagstyle: "is-success"
        url: "http://192.168.7.254/admin/"
        target: "_blank" # optional html a tag target attribute

  - name: "Management - Services"
    icon: "fa-solid fa-folder-open"
    items:
      - name: "Cockpit"
        logo: "assets/tools/cockpit.png"
        subtitle: "... ..."
        tag: "app2"
        tagstyle: "is-success"
        url: "http://192.168.7.254:9090"
        target: "_blank" # optional html a tag target attribute

  - name: "Remote - Services"
    icon: "fa-solid fa-gears"
    items:
      - name: "Unifi Portal"
        logo: "assets/tools/portal.png"
        subtitle: "... ... ..."
        tag: "core"
        tagstyle: "is-warning"
        url: "https://unifi.ui.com/consoles"
        target: "_blank" # optional html a tag target attribute
      - name: "Resolvr"
        logo: "assets/tools/ghost.png"
        subtitle: ""
        tag: "remote"
        tagstyle: "is-danger"
        url: "http://192.168.10.254:85/"
#        target: "_blank" # optional html a tag target attribute

