---
title: "Pluto Estate Dashboard"
subtitle: "Home"

header: false
footer: '<p><a href="https://redi1.soccerstreams.net/"><i class="fas fa-futbol"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www3.gogoanime.cm/category/shingeki-no-kyojin-the-final-season-part-2"><i class="fas fa-dragon"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://anydesk.com/uk/downloads/thank-you?dv=win_exe"><i class="fas fa-download"></i></a></p>'
target: "_blank" # optional html a tag target attribute

stylesheet:
  - "assets/custom.css"

columns: "4" # Change this to any number: (1, 2, 3, 4, 6, 12)
colors:
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

  light:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

links:
 - name: "Google.co.uk"
   icon: "fa-brands fa-google"
   url: "https://www.google.co.uk/?gws_rd=ssl"
   target: "_blank" # optional html a tag target attribute
 - name: "CloudFlare"
   icon: "fa-brands fa-cloudflare"
   url: "https://www.youtube.com/"
   target: "_blank" # optional html a tag target attribute
 - name: "Youtube"
   icon: "fa-brands fa-youtube"
   url: "https://www.youtube.com/"
   target: "_blank" # optional html a tag target attribute
 - name: "Github"
   icon: "fab fa-github-alt"
   url: "https://github.com/cityplug?tab=repositories"
   target: "_blank" # optional html a tag target attribute
 - name: "Router"
   icon: "fa-regular fa-map"
   url: "https://192.168.7.1"
   target: "_blank" # optional html a tag target attribute 

services:
  - name: "//Hardware"
    icon: "fa-solid fa-server"
    items:
      - name: "Wireguard"
        logo: "assets/tools/wireguard.png"
        subtitle: "... ..."
        tag: "app"
        tagstyle: "is-link"
        url: "http://192.168.7.254:14792/"
        target: "_blank" # optional html a tag target attribute
      - name: "ReoLink"
        logo: "assets/tools/reo.png"
        subtitle: "... ..."
        tag: "app"
        tagstyle: "is-link"
        url: "http://192.168.7.***/"
        target: "_blank" # optional html a tag target attribute

  - name: "//Services"
    icon: "fa-solid fa-gears"
    items:
      - name: "Pihole"
        logo: "assets/tools/pihole.png"
        subtitle: "... ..."
        tag: "service"
        tagstyle: "is-success"
        url: "http://192.168.7.254/admin/"
        target: "_blank" # optional html a tag target attribute
      - name: "Unifi Controller"
        logo: "assets/tools/controller.png"
        subtitle: "... ... ..."
        tag: "core"
        tagstyle: "is-link"
        url: "https://unifi.cityplug.co.uk:8443"
        target: "_blank" # optional html a tag target attribute
      - name: "Unifi Portal"
        logo: "assets/tools/portal.png"
        subtitle: "... ... ..."
        tag: "core"
        tagstyle: "is-link"
        url: "https://unifi.ui.com/consoles"
        target: "_blank" # optional html a tag target attribute

  - name: "//Management"
    icon: "fa-solid fa-folder-open"
    items:
      - name: "Cockpit"
        logo: "assets/tools/cockpit.png"
        subtitle: "... ..."
        tag: "link"
        tagstyle: "is-link"
        url: "http://192.168.7.254:9090"
        target: "_blank" # optional html a tag target attribute

  - name: "//Estate"
    icon: "fa-solid fa-house-lock"
    items:
      - name: "Zero"
        logo: "assets/tools/ghost.png"
        subtitle: ""
        tag: "bridge"
        tagstyle: "is-link"
        url: "http://192.168.10.254:85/"
#        target: "_blank" # optional html a tag target attribute
