version: "3.6"

services:

  pihole:
    container_name: pihole
    hostname: pihole.titan
    image: pihole/pihole:latest
    environment:
      WEBTHEME: default-dark
      TZ: Europe/London
      WEBPASSWORD: Szxs234.
      PIHOLE_DOMAIN: titan.local.cityplug
    volumes:
      - /env/appdata/pihole:/etc/pihole/
      - /env/appdata/pihole/dnsmasq:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    cap_add:
      - NET_ADMIN
    restart: always

  homepage:
    container_name: homepage
    hostname: titan.homepage
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - /env/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /env/appdata/homepage/images:/app/public/images
    ports:
      - 85:3000
    restart: always

  db:
    container_name: nextcloud_db
    image: yobasystems/alpine-mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /var/lib/docker/volumes/Nextcloud_Database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=T0day.T1jan333
      - MYSQL_PASSWORD=Szxs9876@@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: nextcloud
    hostname: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
#      - /var/lib/docker/volumes/Nextcloud_Application:/var/www/html
      - /env/appdata/nextcloud/:/var/www/html
      - /env/appdata/nextcloud/config:/var/www/html/config
      - /env/appdata/nextcloud/custom_apps:/var/www/html/custom_apps
      - /env/appdata/nextcloud/data:/var/www/html/data
      - /env/appdata/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=Szxs9876@@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_UPLOAD_LIMIT=16G
      - PHP_MEMORY_LIMIT=16G

  npm-app:
    container_name: npm-app
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 90:80
      - 91:81
      - 443:443
    volumes:
      - /env/appdata/npm/config.json:/app/config/production.json
      - /env/appdata/npm/data:/data
      - /env/appdata/npm/letsencrypt:/etc/letsencrypt
    restart: always
  npm-db:
    container_name: npm-db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=T0day.T1jan333
      - MYSQL_PASSWORD=T0day.T1jan333
      - MYSQL_DATABASE=npm
      - MYSQL_USER=focal
    volumes:
      - /env/appdata/npm/data/mysql:/var/lib/mysql
    restart: always