version: "3.3"

services:

  pihole:
    container_name: pihole
    hostname: pihole.titan
    image: pihole/pihole:latest
    environment:
      WEBTHEME: default-dark
      TZ: Europe/London
      WEBPASSWORD:
      PIHOLE_DOMAIN: titan.local.cityplug
    volumes:
      - /env/appdata/pihole:/etc/pihole/
      - /env/appdata/pihole/dnsmasq:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
#      - 443:443/tcp
    cap_add:
      - NET_ADMIN
    restart: always

  homepage:
    container_name: homepage
    hostname: titan.homepage
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - /env/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /env/appdata/homepage/images:/app/public/images
    ports:
      - 8921:3000
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    hostname: watchtower
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev-self-contained
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    command:  --interval 3600 --cleanup
    restart: unless-stopped

  app:
    container_name: nextcloud_app
    image: nextcloud
    restart: always
    ports:
      - 8123:80
    links:
      - db
    volumes:
      - /env/appdata/nextcloud/:/var/www/html
      - /env/appdata/nextcloud/config:/var/www/html/config
      - /env/appdata/nextcloud/custom_apps:/var/www/html/custom_apps
      - /env/appdata/nextcloud/data:/var/www/html/data
      - /env/appdata/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=T0day.T1jan333
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  db:
    container_name: nextcloud_db
    image: yobasystems/alpine-mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /env/appdata/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=T0day.T1jan333
      - MYSQL_PASSWORD=T0day.T1jan333
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  npm-app:
    container_name: npm-app
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 90:80
      - 91:81
      - 443:443
    volumes:
      - /opt/titan/.scripts/npm/config.json:/app/config/production.json
      - /env/appdata/npm/data:/data
      - /env/appdata/npm/letsencrypt:/etc/letsencrypt
    restart: always
  npm-db:
    container_name: npm-db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=T0day.T1jan333
      - MYSQL_PASSWORD=T0day.T1jan333
      - MYSQL_DATABASE=npm
      - MYSQL_USER=focal
    volumes:
      - /env/appdata/npm/data/mysql:/var/lib/mysql
    restart: always